---
menu:
  - entry: "Linux Distribution"
    build:
      var_files:
        - "vsphere.pkrvars.hcl"
        - "build.pkrvars.hcl"
        - "ansible.pkrvars.hcl"
        - "proxy.pkrvars.hcl"
        - "common.pkrvars.hcl"
    submenu:
      - entry: "Ubuntu Server 22.04 LTS (cloud-init)"
        build:
          path: "builds/ubuntu/22-04-lts/"
          var_files:
            - "network.pkrvars.hcl"
            - "linux-storage.pkrvars.hcl"
      - entry: "Red Hat Enterprise Linux 8"
        build:
          path: "builds/rhel/8/"
          var_files:
            - "network.pkrvars.hcl"
            - "linux-storage.pkrvars.hcl"
            - "rhsm.pkrvars.hcl"
      - entry: "Red Hat Enterprise Linux 9"
        build:
          path: "builds/rhel/9/"
          var_files:
            - "network.pkrvars.hcl"
            - "linux-storage.pkrvars.hcl"
            - "rhsm.pkrvars.hcl"